### PR TITLE
Rename `cvd` to `cf` to de-conflict with AOSP cvd tool

### PR DESCRIPTION
**Pull request by Databean**
i.e. https://cs.android.com/android/platform/superproject/+/master:device/google/cuttlefish/host/commands/cvd/server_command.cpp;l=53;drc=3a8b5a8815d5f8b72641099b711e0ae159ef2b3f

### CODE REVIEW

**Comment by Databean** [comment]
@pcc does this work for you?

**Comment by pcc** [comment]
Sure, works for me.

**Comment by kwstephenkim** [comment]
I guess this seems to work as long as we change the line 7 of the cf file. It is now `cvd` while it should be `cf`, I guess.

**Review by kwstephenkim — APPROVED** [review]
Looks good to me now.

**Comment by Databean** [comment]
Thanks!

**Pull request merged**
