### PR TITLE
Implement cvd env call

### PR DESCRIPTION
**Pull request by 0405ysj**
This PR needs this change in AOSP.
https://android-review.googlesource.com/c/device/google/cuttlefish/+/2648603

This PR is testable with following commands.
```
$ curl -k --request POST "https://localhost:1443/devices/cvd-1/env/call/OpenwrtControlService/LuciRpc" \
--data "{subpath:'uci', method:'get_all', params:['network']}"
```
```
$ curl -k --request POST "https://localhost:1443/devices/cvd-1/env/call/WmediumdService/ListStations" \
--data "{}"
```

### CODE REVIEW

**Review by ikicha — APPROVED** [review]

**Comment by ikicha** [comment]
Please add grpc and protobuf lib into internal BUILD file.

**Review by ikicha — APPROVED** [review]

**Comment by ikicha** [comment]
Can we check if [operator/protobuf/control_env_proxy.pb.go](https://github.com/google/android-cuttlefish/pull/312/commits/2176f92e9c333f1e1cd45baeaa05e4e72fcbac31#diff-850efb4e19ab0969d595f5c292fe7c214c9891fe1dd088685df2b0b2137c33eb) comes from current proto files?

**Comment by 0405ysj** [comment]
Current proto files generates pb.go files correctly. Source and destination was re-defined with changing following files in the latest commit.

- frontend/debian/rules
- frontend/src/liboperator/protobuf/control_env_proxy.proto

The reason why I moved directory is about resolving error while migrating this PR with internal BUILD file. 

BTW, I cannot modify BUILD file only before applying this PR into the change, because of file addition.

**Comment by 0405ysj** [comment]
@ikicha Could you merge this PR? I don't have write access in this repo.

**Pull request merged**
